require 'test_helper'

class FlavorStatsControllerTest < ActionController::TestCase
  
  # All of this test gubbins was generated by rails.  In looking into it, 
  # because I'm using devise, I need a logged in user to exercise the 
  # controllers.  That will be something for later.  The most important thing
  # right now is to test the models.
  
  # setup do
  #   @flavor_stat = flavor_stats(:one)
  # end

  # test "should get index" do
  #   get :index
  #   assert_response :success
  #   assert_not_nil assigns(:flavor_stats)
  # end

  # test "should get new" do
  #   get :new
  #   assert_response :success
  # end

  # test "should create flavor_stat" do
  #   assert_difference('FlavorStat.count') do
  #     post :create, flavor_stat: {  }
  #   end

  #   assert_redirected_to flavor_stat_path(assigns(:flavor_stat))
  # end

  # test "should show flavor_stat" do
  #   get :show, id: @flavor_stat
  #   assert_response :success
  # end

  # test "should get edit" do
  #   get :edit, id: @flavor_stat
  #   assert_response :success
  # end

  # test "should update flavor_stat" do
  #   patch :update, id: @flavor_stat, flavor_stat: {  }
  #   assert_redirected_to flavor_stat_path(assigns(:flavor_stat))
  # end

  # test "should destroy flavor_stat" do
  #   assert_difference('FlavorStat.count', -1) do
  #     delete :destroy, id: @flavor_stat
  #   end

  #   assert_redirected_to flavor_stats_path
  # end
end
